#!/bin/sh
# Update LXDE menu:

echo "Updating LXDE menu: update-desktop-database"
for x in `ps -C lxsession -o user=`; do su --login $x -c "rm ~/.cache/menus/* >/dev/null 2>&1; /usr/libexec/menu-cache/menu-cached >/dev/null 2>&1; lxpanelctl restart"; done
update-desktop-database

