#!/bin/bash

# Custom porteus tweaks:
#sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' usr/libexec/udisks-daemon                 # disable showexec flag
#sed -i usr/share/applications/gpicview.desktop -e 's/Utility;//g'                            # move gpicview from Utilities to Graphics category

# Fix ugly looking icons:
#sed -i -r s^Icon=.*$^Icon=utilities-terminal^g usr/share/applications/uxterm.desktop
#sed -i -r s^Icon=.*$^Icon=go-down^g usr/share/applications/gftp.desktop

#remove version of libssp, libgmp, libquadmath and libltdl that doesn't belong based on arch
#NOTE - libgmp and libssp are now in core or xorg, so have been dropped from 003 tree
# not sure about libltdl

#if [ `arch` = "x86_64" ]; then
#  rm usr/lib/libquadmath*
#  rm usr/lib/libltdl*
#  rmdir usr/lib
#fi

#if [ `arch` = "i686" ]; then
#  rm usr/lib64/libquadmath*
#  rm usr/lib64/libltdl*
#  rmdir usr/lib64
#fi

# Remove unnecessary stuff:
rm -rf usr/info/*
rm -rf usr/doc/*
rm -rf usr/man/man2/*
rm -rf usr/man/man3/*
rm -rf usr/man/man4/*
rm -rf usr/man/man6/*
rm -rf usr/man/man9/*
rm -rf usr/share/gtk-doc/*
rm -rf usr/share/applications/mimeinfo.cache
rm -rf usr/share/lxde/wallpapers/*
rm -rf usr/share/mime/mime.cache
rm -rf usr/share/xsessions/openbox-gnome.desktop usr/share/xsessions/openbox-kde.desktop
rm -rf var/log/scripts/*
rm -rf var/log/setup/*
rm -rf usr/share/gtk-3.0/demo
rm -rf usr/share/devhelp
rm -rf usr/share/gnome
rm -rf usr/share/icons/Tango
rm -rf usr/share/help

#remove large hicolor icons and 64 icons in Humanity if present
( cd usr/share/icons; for a in 64 128x128 256x256 64x64 96x96 160x160 192x192 72x72; do find . -name $a|xargs rm -rf; done )

##drop extra audacious skins
#( cd usr/share/audacious/Skins; ls|grep -v Default|xargs rm -rf )

##gparted needs root perms so open it with kstuss
#sed -i /Exec=/'s@= /usr/sbin/gparted@= ktsuss /usr/sbin/gparted@g' usr/share/applications/gparted.desktop

##move geany from "development" section to "accessories"
#sed -i /Categories/'s/Development/Utility/g' usr/share/applications/geany.desktop

##Only display evince in "Office", not "Graphics"
#sed -i -r 's^Categories=.*$^Categories=Viewer;Office;GTK;^g' usr/share/applications/evince.desktop

## Strip transmission from cli stuff:
#pushd usr/bin && ls transmission* | grep -v gtk | xargs rm && popd

##ONLY FOR LXDE - DON'T DO THIS IN XFCE
##remove xfwm4 theme from Evolve
#rm -rf usr/share/themes/Evolve/xfwm4

# Set default perms, extract compressed files, strip debugging symbols:
echo "Changing permissions..."
find ./ -type d | xargs chmod -v 755 >/dev/null 2>&1
echo "Extracting All manpages..."
find . | grep .gz | xargs gunzip >/dev/null 2>&1
echo "stripping Unneeded Symbols..."
find . | xargs file | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded >/dev/null 2>&1

## Create dir for dropping stuff:
#mkdir -p /home/work/changes/togo/man /home/work/changes/togo/locale /home/work/changes/a.out /home/work/changes/h.out

## Drop static libs:
#pack=`find . -name "*.a"`
#target=/home/work/changes/a.out
#for a in $pack; do
#    cp -a --parents $a $target
#    rm $a
#done

## move headers to separate module:
#pack=`find . -name "*.h"`
#target=/home/work/changes/h.out
#for a in $pack; do
#    cp -a --parents $a $target
#    rm $a
#done
##drop folders too
#rm -rf usr/include/*

##get .gir files too
#pack=`find . -name "*.gir"`
#target=/home/work/changes/h.out
#for a in $pack; do
#    cp -a --parents $a $target
#    rm $a
#done

## Move translations/localized man pages:
#echo "moving locales"
#cp -r usr/share/locale /home/work/changes/togo && rm -r usr/share/locale/*

#for x in `ls usr/man | grep -v man`; do
#    cp -r usr/man/$x /home/work/changes/togo/man
#    rm -r usr/man/$x
#done

##build modules out of everything you dropped - this step is optional
#for a in togo a.out h.out; do
#  dir2xzm /home/work/changes/$a /tmp/lxde-$a.xzm
#done


#echo "move changes"
